(define (product-rec term a next b)
  (if (> a b)
      1
      (* (term a)
         (product-rec term (next a) next b))))
(define (inc n) (+ n 1))
(define (identity x) x)
(define (factorial n) (product-rec identity 1 inc n))
(define (product-term i) 
    (if (even? i) 
        (/ (+ i 2) (+ i 1))
        (/ (+ i 1) (+ i 2))
        ))
  (* 4 (product-rec product-term 1.0 inc 1000.0))